# Generated by Django 2.1.2 on 2019-01-03 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnCS', '0003_exercise_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='learnCS.Lesson')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='solution',
        ),
    ]
