# Generated by Django 2.1.2 on 2019-01-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnCS', '0004_auto_20190103_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='lesson',
            new_name='exercise',
        ),
    ]
