# Generated by Django 2.1.2 on 2019-01-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnCS', '0005_auto_20190103_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='course',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
