# Generated by Django 2.1.2 on 2019-01-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnCS', '0006_auto_20190103_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
